# This is the configuration file for the application
version: 1.0.0

# Define the name of the annotator and the labels for the annotation
annotator: name_of_annotator
labels: 
    - "1: pleasant"
    - "2: non-pleasant"
    - "3: N/A"

# Define the backend for selecting the samples. Currently supported values are 
# 'farthest-first', 'random', and 'ordered'.
backend:
  name: "ordered"
  kwargs:
    source_path: 'data/highdim_features_simulated_audio_data_subset.npy'


# Define the dimensionality reductions that the user can use
dim_reductions:
  umap:
    n_components: 2
    n_neighbors: 2 # NOTE THAT this is not a very reasonable value (selected for this four-sample demo dataset)
    normalize: true
    metric: "cosine"
  pca:
    n_components: 2
  tsne:
    n_components: 2
    perplexity: 2 # NOTE THAT this is not a very reasonable value (selected for this four-sample demo dataset)
    init: "pca"
    default: true


# Define the widgets that are displayed on the application
# Each widget defines its name, type, position and possible keyword arguments.
# These arguments should always contain either 'source_dirs' or 'source_path'
# argument, which contain a list of paths pointing the data source that the
# widget should display.
widgets:
  - name: "waveform_v1"
    wtype: "waveform"
    position:
      row: 1
      col: 0
      rowspan: 1
      colspan: 1
    kwargs:
      sr: 2000
      plot_titles: {0: 'Channel A',
                    1: 'Channel B'}
      source_dirs:
        - 'data/numpy_files_channel_a_downsampled'
        - 'data/numpy_files_channel_b_downsampled'
  
  - name: "spectrogram_v1"
    wtype: "spectrogram"
    position: 
      row: 0
      col: 1
      rowspan: 1
      colspan: 1
    kwargs:
      n_mel: 40
      hop_ms: 10
      sr: 16000
      source_dirs:
        - 'data/logmel_feats_channel_a' # This folder contains .npy files, each with the dimensions [num_mel_bins, num_frames]
  
  - name: "audio_v1"
    wtype: "audio"
    position:
      row: 0
      col: 0
      rowspan: 1
      colspan: 1
    kwargs:
      auto_play: True
      source_dirs:
          - 'data/wav_files_channel_a'

  - name: "scatter_v0"
    wtype: "scatter"
    position:
      row: 1
      col: 1
      rowspan: 1
      colspan: 1
    kwargs:
      source_path: "data/highdim_features_simulated_audio_data_subset.npy"
      base_marker_size: 25
